### ISSUE TITLE
Number of open files Debug Mode

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#1073]
In long PyAutoLens sensitivity mapping runs, they crash with the following error:

```
Traceback (most recent call last):
  File "/cosma/home/dp004/dc-nigh1/subhalo/cosma/runners/sensitivity_pix.py", line 305, in <module>
    fit()
  File "/cosma/home/dp004/dc-nigh1/subhalo/cosma/runners/sensitivity_pix.py", line 288, in fit
    subhalo_result = slam.subhalo.sensitivity_imaging_pix.run(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/subhalo/slam/subhalo/sensitivity_imaging_pix.py", line 742, in run
    result = sensitivity.run()
             ^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/grid/sensitivity/__init__.py", line 162, in run
    for result in process_class.run_jobs(
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/__init__.py", line 22, in run_jobs
    yield job_.perform()
          ^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/grid/sensitivity/job.py", line 183, in perform
    perturb_result = self.perturb_fit_cls(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/subhalo/slam/subhalo/sensitivity_imaging_pix.py", line 452, in __call__
    return search.fit(model=model, analysis=analysis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 594, in fit
    result = self.start_resume_fit(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 101, in decorated
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 721, in start_resume_fit
    search_internal = self._fit(
                      ^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/search/nest/nautilus/search.py", line 149, in _fit
    search_internal = self.fit_multiprocessing(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/PyAutoFit/autofit/non_linear/search/nest/nautilus/search.py", line 255, in fit_multiprocessing
    search_internal = self.sampler_cls(
                      ^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/lib/python3.12/site-packages/nautilus/sampler.py", line 290, in __init__
    pool[i] = NautilusPool(pool[i], likelihood=self.likelihood)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/home/dp004/dc-nigh1/PyAuto/lib/python3.12/site-packages/nautilus/pool.py", line 60, in __init__
    self.pool = Pool(pool, initializer=initialize_worker,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/cosma/local/Python/3.12.4/lib/python3.12/multiprocessing/popen_fork.py", line 65, in _launch
    child_r, parent_w = os.pipe()
                        ^^^^^^^^^
OSError: [Errno 24] Too many open files
```

It is hard to be sure why there are too many open files, it might be autofit hard-disk output, autolens visualization or some other part of the code. It is probably an indication of a leak somewhere which needs identifying and fixing.

Users have reported to me memory issues with visualization, whereby memory usage increases for longer autolens runs with the only feasible explanation being bad garbage collection from Python.

Could we have a DEBUG mode implemented in autofit, which when an enviroment variable is set prints out the number of open files (and any other useful related information) everytime a search begins and when a search runs its `perform_update` method? My hope is this will allow me to identify under what circumstances the number of files is increasing.

The error above came from a long HPC run, I am triyng to figure out if I can reproduce it locally.

**Comment by Jammy2211** [comment]
As well as a debug mode, we shiould have a warning always print when the number of files exceeds some config file (e.g. over 50 or something suspiciously large).
