### ISSUE TITLE
Commented out dataset_name query

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#165]
I have commented this feature out for now, as it leads to the following error when trying to make a database:

`Emcee has finished run - you may now continue the notebook.
Aggregator loading phases... could take some time.

 A total of 3 phases and results were found.
Traceback (most recent call last):
  File "scripts/features/database.py", line 155, in <module>
    agg.add_directory(path.join("output", "features", "database"))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator.py", line 244, in add_directory
    fit.dataset_name = fit["dataset"].name
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/model/fit.py", line 127, in __getitem__
    return getattr(
AttributeError: 'Fit' object has no attribute 'dataset'`

I have tried naming the Analysis attribute dataset and giving it a name, but it does not work. This makes me very uncomfortable anyway, as it means one has to write their model-specific objects in a way that feels uncessary.

I think we need to rethink how dataset naming and querying is going to work.

**Comment by Jammy2211** [comment]
I think I have a better way to handle dataset names.

The Aggregator currently support an info_dict, whereby if I pass the following into the fit it becomes a pickled object that I can load:

`
info = {"date_of_observation": "01-02-18", "exposure_time": 1000.0}

result = emcee.fit(model=model, analysis=analysis, info=info)
`

Instead of having the dataset name be an attribute of the data (which requires that the data be written in a specific way) can we make the info a queryable object? So that I could find all fits whose info object has a certain dataset name. We could also require on something like data_of_observation above, to find all model-fits using data before a certain date, for example.

**Comment by Jammy2211** [comment]
This would be a nice API:

```
    info = {"dateset_name": f"gaussian_{dataset_index}"}

    emcee.fit(model=model, analysis=analysis, info=info)

    agg_query = agg.query(agg.info["dataset_name"] == "gaussian_10")
    
    samples_gen = agg_query.values("samples")
```
