### ISSUE TITLE
Issue with expectation + Dynesty

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#253]
The following script tries to fit a model via expectation using dynesty:

`https://github.com/Jammy2211/autofit_workspace/blob/master/scripts/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation.py`

I think you said you understood this issue last week and knew how to fix it, just putting it here so we dont forget.

**Comment by rhayes777** [comment]
What was the issue?

**Comment by Jammy2211** [comment]
Haha I forgot to copy and paste it:

```
2021-06-09 09:12:46,036 - tutorial_3_expectation_propagation - INFO - Removing zip file
Traceback (most recent call last):
  File "scripts/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation.py", line 172, in <module>
    collection = factor_graph.optimise(laplace)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/declarative.py", line 146, in optimise
    updated_model = opt.run(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/expectation_propagation.py", line 355, in run
    model_approx, status = optimiser.optimise(factor, model_approx)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 260, in optimise
    new_model_dist = MeanField({
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 262, in <dictcomp>
    result.model.prior_with_id(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 816, in prior_with_id
    return self._prior_id_map[
KeyError: 0
```

**Comment by rhayes777** [comment]
Oh yeah this is that known issue
