### ISSUE TITLE
Issue with parallel job on autofit_workspace_test

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#269]
The following test gives me the error below:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/parallel/DynestyStatic_x4.py

```
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,776 - process 1 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,777 - process 0 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,777 - process 3 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,778 - process 2 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,778 - process 1 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,779 - process 0 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,779 - process 3 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,779 - process 2 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,780 - process 1 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,780 - process 0 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,781 - process 3 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
2021-06-15 19:49:17,781 - process 2 - ERROR - too many values to unpack (expected 4)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 150, in run
    job.perform(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/parallel/sneaky.py", line 121, in perform
    return self.function(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dynesty/bounding.py", line 1557, in _ellipsoids_bootstrap_expand
    points, pointvol, vol_dec, vol_check = args
ValueError: too many values to unpack (expected 4)
```

**Comment by Jammy2211** [comment]
Replacing this:

```
        return self.function(
            args
        )
```

With this:

```
        try:
            return self.function(
                args
            )
        except ValueError:
            return likelihood_function(
                self.args
            )
```

Seems to fix it...?
