### ISSUE TITLE
Cannot get search queries to work

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#270]
The following example script doesn't work at the end:

`https://github.com/Jammy2211/autofit_workspace_test/blob/main/database/search_queries.py`

With the following error:

```
(PyAuto) jammy@DESKTOP-H143S82:/mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test$ python database/search_queries.py
2021-06-16 10:39:32,210 - autoconf.conf - WARNING - Pushing new config with path /mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/config
2021-06-16 10:39:32,255 - autoconf.conf - WARNING - No configuration found at path /mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/config
2021-06-16 10:39:32,279 - search_queries - INFO - Creating search
2021-06-16 10:39:32,279 - search_queries - INFO - Starting search
2021-06-16 10:39:32,297 - search_queries - INFO - Already completed, skipping non-linear search.
2021-06-16 10:39:32,333 - search_queries - INFO - Removing zip file
2021-06-16 10:39:32,378 - autofit.database.migration.migration - INFO - Performing migration from None to 93c237d700a20c14dd2f49411157c2d2 in 1 steps
2021-06-16 10:39:32,379 - autofit.database.migration.migration - INFO - revision_id updated to 93c237d700a20c14dd2f49411157c2d2
2021-06-16 10:39:32,381 - autofit.database.aggregator.aggregator - INFO - 0 fit(s) found matching query
2021-06-16 10:39:32,383 - autofit.database.aggregator.aggregator - INFO - 0 fit(s) found matching query
Total Samples Objects via `path_prefix` model query =  0

Traceback (most recent call last):
  File "database/search_queries.py", line 119, in <module>
    len(agg_query),
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 169, in __len__
    return len(self.fits)
TypeError: object of type 'NamedQuery' has no len()
```

**Comment by rhayes777** [comment]
Use agg.search instead of agg.fit
