### ISSUE TITLE
Give more info when database build fails due to unique id error

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#316]
I get the following error building a database:

```
Traceback (most recent call last):
  File "database/build.py", line 51, in <module>
    agg.add_directory(directory=path.join("output", database_name))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 448, in add_directory
    self.session.commit()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 419, in execute
    n.execute_aggregate(self, set_)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 697, in execute_aggregate
    persistence.save_obj(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 605, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: fit.id
[SQL: INSERT INTO fit (id, is_complete, max_log_likelihood, parent_id, is_grid_search, unique_tag, name, path_prefix, model_id, instance_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('51d3d1123b18981ac2a1ea25da2dde70', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source', None, 1, 2), ('6f2c2f9969d62b2ef1c11443cd6cd422', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source', None, 3, 4), ('7c407fc45170f894889b5f7ba47e32c3', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source', None, 5, 6), ('8cffcabf9dd7a6782214150c34a5aae6', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source', None, 7, 8), ('c88e39d73d851776399001c45221d227', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source', None, 9, 10), ('053cc4083e66994ef62f0020a431140d', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source_grad', None, 11, 12), ('501b587b737e02c4373a53ed2e35f507', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source_grad', None, 13, 14), ('564d262d8b26ac558b7e3e9d0cd24d3e', 0, None, None, None, 'f390w', 'mass_light_dark[1]_light[fixed]_mass[light_dark]_source_grad', None, 15, 16)  ... displaying 10 of 77 total bound parameter sets ...  ('566b3c5708e4fb5cdfa86d24afb72020', 1, None, None, None, 'f814w', 'source_inversion[4]_mass[total]_source[fixed]__hyper', None, 151, 152), ('6eb0ecdb942be53c201c5a895c36a738', 1, None, None, None, 'f814w', 'source_parametric[1]_mass[total]_source[parametric]', None, 153, 154))]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

Could you have it print the specific duplicated id?

**Comment by rhayes777** [comment]
51d3d1123b18981ac2a1ea25da2dde70

**Comment by rhayes777** [comment]
Do you actually need me to do this or are you happy that you can find the identifier in that stacktrace?

**Comment by Jammy2211** [comment]
Do it for the benefit of other users.

**Comment by rhayes777** [comment]
Hmm might be a bit tricky as when commits it could be any of a number of fit ids. Also the error isn't specific to failure for fit ids. It could also occur because integrity is violated elsewhere.

I might be able to extract the required information from the error I guess

**Comment by Jammy2211** [comment]
If its not worth the effort leave it, didnt think itd be so tricky!
