### ISSUE TITLE
Prior ID / Linking issue

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#323]
On the branch `feature/prior_match`, the implementation is still passing priors incorrect, for example in the `prior_id` example the `model.info` file in the source_inversion[2] pipeline changes from:

```
                elliptical_comps_0                                                        GaussianPrior, mean = -0.05939735044952736, sigma = 0.2
                elliptical_comps_1                                                        GaussianPrior, mean = -0.05963959789156295, sigma = 0.2
            einstein_radius                                                               GaussianPrior, mean = 1.0318826192472927, sigma = 0.2579706548118232
        shear
            elliptical_comps
                elliptical_comps_0                                                        GaussianPrior, mean = -0.02314872871131792, sigma = 0.05
                elliptical_comps_1                                                        GaussianPrior, mean = -0.016465824358825293, sigma = 0.05
```

too:

```
                elliptical_comps_0                                                        GaussianPrior, mean = -0.016037279103709026, sigma = 0.2
                elliptical_comps_1                                                        GaussianPrior, mean = -0.011676543838111226, sigma = 0.2
            einstein_radius                                                               GaussianPrior, mean = 0.09528053930149398, sigma = 0.023820134825373495
        shear
            elliptical_comps
                elliptical_comps_0                                                        GaussianPrior, mean = -0.02314872871131792, sigma = 0.05
                elliptical_comps_1                                                        GaussianPrior, mean = -0.016465824358825293, sigma = 0.05
```

The new values of priors can be associated with results from the previous phase. For example, the einstein_radius value of `(e.g. 0.09528053930149398)` comes from the result of the `lens.bulge.intensity` in the previous model-fit.

**Comment by Jammy2211** [comment]
Furthermore, base runs of a lens modeling pipeline (e.g. without old results, just from scratch) give the following error and dont run at all :P.

```
Pushing new config with path /mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/config/slam
2021-07-23 10:05:07,472 - autoconf.conf - WARNING - Pushing new config with path /mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/config
2021-07-23 10:05:08,584 - autoconf.conf - WARNING - Pushing new config with path /mnt/c/Users/Jammy/Code/PyAuto/PyAutoArray/autoarray/config
2021-07-23 10:05:09,043 - autoconf.conf - WARNING - Pushing new config with path /mnt/c/Users/Jammy/Code/PyAuto/PyAutoGalaxy/autogalaxy/config
2021-07-23 10:05:09,435 - autoconf.conf - WARNING - Pushing new config with path /mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/config
2021-07-23 10:05:15,315 - autofit.non_linear.abstract_search - INFO - Creating search
2021-07-23 10:05:15,315 - source_parametric[1]_light[parametric] - INFO - Starting search
2021-07-23 10:05:15,320 - source_parametric[1]_light[parametric] - INFO - Saving path info
2021-07-23 10:05:15,357 - source_parametric[1]_light[parametric] - INFO - Not complete. Starting non-linear search.
2021-07-23 10:05:15,358 - source_parametric[1]_light[parametric] - INFO - number_of_cores == 1...
2021-07-23 10:05:15,358 - source_parametric[1]_light[parametric] - INFO - ...not using pool
2021-07-23 10:05:15,393 - source_parametric[1]_light[parametric] - INFO - No Dynesty samples found, beginning new non-linear search.
2it [00:00, 10.51it/s, +75 | bound: 0 | nc: 1 | ncall: 77 | eff(%): 100.000 | loglstar:   -inf < -240961.139 <    inf | logz: -240965.627 +/-    nan | dlogz:  0.761 >  0.084]
2021-07-23 10:05:15,605 - source_parametric[1]_light[parametric] - INFO - 2500 Iterations: Performing update (Visualization, outputting samples, etc.).
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/prior_model.py", line 279, in _instance_for_arguments
    prior_arguments[name] = arguments[prior]
KeyError: <LogUniformPrior id=180 lower_limit=0.99999 upper_limit=1.0000001>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples.py", line 198, in instance_for_model
    return model.instance_from_path_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 912, in instance_from_path_arguments
    return self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 54, in wrapper
    return func(s, arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/collection.py", line 167, in _instance_for_arguments
    value = value.instance_for_arguments(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 795, in instance_for_arguments
    return self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 54, in wrapper
    return func(s, arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/collection.py", line 167, in _instance_for_arguments
    value = value.instance_for_arguments(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 795, in instance_for_arguments
    return self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 54, in wrapper
    return func(s, arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/prior_model.py", line 273, in _instance_for_arguments
    ] = prior_model.instance_for_arguments(arguments, )
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 795, in instance_for_arguments
    return self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 54, in wrapper
    return func(s, arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/prior_model.py", line 281, in _instance_for_arguments
    raise KeyError(
KeyError: 'No argument given for prior intensity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "slam/with_lens_light/source_inversion/mass_total/no_hyper.py", line 127, in <module>
    source_parametric_results = slam.source_parametric.with_lens_light(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/source_parametric.py", line 201, in with_lens_light
    result_1 = search.fit(model=model, analysis=analysis, info=settings_autofit.info)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 467, in fit
    self._fit(model=model, analysis=analysis, log_likelihood_cap=log_likelihood_cap)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/nest/dynesty/abstract.py", line 194, in _fit
    self.perform_update(model=model, analysis=analysis, during_analysis=True)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 593, in perform_update
    instance = samples.max_log_likelihood_instance
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples.py", line 424, in max_log_likelihood_instance
    return self.max_log_likelihood_sample.instance_for_model(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples.py", line 209, in instance_for_model
    self.parameter_lists_for_model(model)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples.py", line 122, in parameter_lists_for_model
    return [
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples.py", line 123, in <listcomp>
    self.kwargs[path]
KeyError: ('galaxies', 'lens', 'disk', 'intensity')
```

**Comment by Jammy2211** [comment]
Even the master branch has been tanked lol

**Comment by rhayes777** [comment]
Thank god we have integration tests. Will dig into this
