### ISSUE TITLE
Change in numerical values of LogUniformPrior

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#342]
The new `LogUniformPriror` gives different mappings of unit to physical parameters than the old one. To retain BC for existing results. 

I have fixed this by over writing the `value_for` method with the old method (which doesn't seem to have broken any unit testS) but its worth figuring out whats going on.

**Comment by Jammy2211** [comment]
In fact, pickling of the `LogUniformPrior` is tanking the whole run:

```
2021-08-20 17:52:16,898 - autoconf.conf - WARNING - Pushing new config with path /mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/config
2021-08-20 17:52:16,989 - autofit.non_linear.abstract_search - INFO - Creating search
2021-08-20 17:52:16,989 - DynestyStatic - INFO - Starting search
2021-08-20 17:52:16,993 - DynestyStatic - INFO - Saving path info
Traceback (most recent call last):
  File "scripts/searches/nest/DynestyStatic.py", line 92, in <module>
    result = dynesty.fit(model=model, analysis=analysis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 455, in fit
    self.paths.save_all(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/directory.py", line 159, in save_all
    self.save_object("search", self.search)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/directory.py", line 57, in save_object
    dill.dump(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 267, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.8/pickle.py", line 485, in dump
    self.save(obj)
  File "/usr/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "/usr/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "/usr/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "/usr/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.8/pickle.py", line 690, in save_reduce
    save(args)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.8/pickle.py", line 899, in save_tuple
    save(element)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 1390, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "/usr/lib/python3.8/pickle.py", line 1068, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <class 'autofit.messages.abstract.ShiftedUniformMessage'>: it's not found as autofit.messages.abstract.ShiftedUniformMessage
```

I have commented out the new LogUniformPrior and replaced it with the old one for now, to fix things.

**Comment by rhayes777** [comment]
Pushed a fix for the second issue. Have you got a test for the first one? They seemed to behave correctly numerically when I tested them.

**Comment by Jammy2211** [comment]
I dont have a test, but I think the value_for method simply gives different results for the old method (above) and the new one.

My prior range was 1e-6 -> 1e-6, the old method got a unit value of 0.5 gave 1.0 where the new method was like 1.023

**Comment by Jammy2211** [comment]
For BC its superflously, as the new priors properly tanks unique identifiers :P. Got an old branch that I think is working as expected, so no biggie until next week.

**Comment by rhayes777** [comment]
Hmm I think there will be small numerical differences regardless because it's computed using a different method.

We can leave in the old value_for without a huge amount of issue I guess but it's not perfect

**Comment by Jammy2211** [comment]
If BC wasnt an issue I'd say just use the new one.

Perhaps have a LogUniformPriorBC class I can use, and we delete when we do a BC purge?

**Comment by rhayes777** [comment]
Yeah I think that could work
