### ISSUE TITLE
id issue with searcxh grid parent

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#378]
Running this script:

https://github.com/Jammy2211/autolens_workspace_test/blob/master/database/directory/subhalo_slam.py

Gives this error:

```
 A total of 4 search_outputs and results were found.
Traceback (most recent call last):
  File "database/directory/subhalo_slam.py", line 179, in <module>
    agg.add_directory(directory=path.join("output", "database", "directory", "subhalo_slam"))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 445, in add_directory
    scraper.scrape()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 62, in scrape
    for grid_search in self._grid_searches():
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 182, in _grid_searches
    fit = self._retrieve_model_fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 211, in _retrieve_model_fit
    return self.session.query(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3534, in __iter__
    self.session._autoflush()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1622, in _autoflush
    self.flush()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 419, in execute
    n.execute_aggregate(self, set_)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 697, in execute_aggregate
    persistence.save_obj(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 205, in save_obj
    for (
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 405, in _organize_states_for_save
    raise orm_exc.FlushError(
sqlalchemy.orm.exc.FlushError: New instance <Fit at 0x7fa359bc04f0> with identity key (<class 'autofit.database.model.fit.Fit'>, ('e806ee4dea44bce2b6f2f5ee68555aef',), None) conflicts with persistent instance <Fit at 0x7fa35b4c42e0>
```

If I comment out parent below, e.g.:

    subhalo_result = subhalo_grid_search.fit(
        model=model,
        analysis=analysis,
        grid_priors=[
            model.galaxies.subhalo.mass.centre_0,
            model.galaxies.subhalo.mass.centre_1,
        ],
        info=settings_autofit.info,
    #    parent=search_no_subhalo,
    )

The bug doesn't happen so defo the new parent stuff.

**Comment by Jammy2211** [comment]
I also think this should give a lens of 4, but it gives a lenth of 1?

```
"""
__Query__
"""
print(len(agg))

agg_grid = agg.grid_searches()

print(len(agg_grid))
```
