### ISSUE TITLE
Desired behaviour of unfinished SearchGridSearch Issue 1

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#396]
I am running the following script and ctrl + c'ing half way through the grid search and commenting out the line:

```
grid_search_result = grid_search.fit(
    model=model, analysis=analysis, grid_priors=[model.gaussian.centre], parent=parent
)
```

https://github.com/Jammy2211/autofit_workspace_test/blob/main/database/directory/grid_search.py

This puts me in a position where I am attempting to scrape a grid search result which is unfinished.

If I set `completed_only=False` or `completed_only=True`, I get the following error:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 112, in _fits
    fit = self._retrieve_model_fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 210, in _retrieve_model_fit
    return self.session.query(
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "database/directory/grid_search.py", line 120, in <module>
    agg.add_directory(directory=path.join("output", "database", "directory", dataset_name))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 445, in add_directory
    scraper.scrape()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 58, in scrape
    for fit in self._fits():
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 127, in _fits
    max_log_likelihood=samples.max_log_likelihood_sample.log_likelihood,
AttributeError: 'NoneType' object has no attribute 'max_log_likelihood_sample'
```

If `completed_only=True`, the desired behaviour is for the directory and grid search to be ignored entirely, given they are not finished.

I have checked that this issue occurs even when there are other results in the directory being scraped (e.g. another GridSearch).

**Comment by rhayes777** [comment]
Missing samples is now handled by the scraper
