### ISSUE TITLE
Unpickling search grid search result issue when building database

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#409]
I attempted to build a SearchGridsearch database and got the following error:

```
2021-11-12 14:32:36,089 - autofit.database.aggregator.scrape - INFO - Scraping directory output/subhalo_source_mask
Aggregator loading search_outputs... could take some time.

 A total of 946 search_outputs and results were found.
2021-11-12 14:34:32,703 - autofit.database.aggregator.scrape - INFO - 946 searches found
2021-11-12 14:34:48,435 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo mass_total[1]_mass[total]_source 8a9db1395c049ca6e7d2ac74311e4f68
2021-11-12 14:34:48,619 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo mass_total[1]_mass[total]_source__hyper_inversion 85e2de99f7d30b1cf5e720f80722554a
2021-11-12 14:34:48,757 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[1]_mass[fixed]_source[inversion_magnification_initialization] be9400b13b1fa090c813fed798e6c914
2021-11-12 14:34:48,873 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[2]_mass[total]_source[fixed] a0d110b880895f20de3d0701fe4468d9
2021-11-12 14:34:48,963 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[3]_mass[fixed]_source[inversion_initialization] 25bea3e70de6689ed40ed9d97520f55d
2021-11-12 14:34:49,037 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[4]_mass[total]_source[fixed] 5919d92008ae473a4ab9041383b67e73
2021-11-12 14:34:49,150 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[4]_mass[total]_source[fixed]__hyper_inversion ec789a6c37cada9d663c9397bb8c0200
2021-11-12 14:34:49,414 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_parametric[1]_mass[total]_source[parametric] a8eea5f8d95b5b737fc6ac11b53969c8
2021-11-12 14:34:49,943 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo subhalo[1]_mass[total_refine] 2aea237054b47782286f42c04f0d11ac
Traceback (most recent call last):
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 727, in _create_filehandle
    f = open(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/cosma/home/dp004/dc-nigh1/subhalo/cosma/batch/no_lens_light/inversion_adapt/root.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "database/build.py", line 51, in <module>
    agg.add_directory(directory=path.join("output", database_name))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 445, in add_directory
    scraper.scrape()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 58, in scrape
    for fit in self._fits():
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 103, in _fits
    identifier = _make_identifier(item)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 244, in _make_identifier
    search = item.search
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/aggregator/search_output.py", line 91, in search
    self.__search = pickle.loads(f.read())
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/dill/_dill.py", line 730, in _create_filehandle
    raise UnpicklingError(err)
_pickle.UnpicklingError: [Errno 2] No such file or directory: '/cosma/home/dp004/dc-nigh1/subhalo/cosma/batch/no_lens_light/inversion_adapt/root.log'
```

I have fixed this by editing the following code to include a pickling exception:

```
    @property
    def search(self) -> abstract_search.NonLinearSearch:
        """
        The search object that was used in this phase
        """
        if self.__search is None:
            try:
                with open(os.path.join(self.pickle_path, "search.pickle"), "r+b") as f:
                    self.__search = pickle.loads(f.read())
            except (FileNotFoundError, dill.UnpicklingError):
                pass
        return self.__search
```

I think the issue is that the `root.log` file uses an incorrect path to be written (e.g. its not using the path to the search results?)

**Comment by Jammy2211** [comment]
This lead to a new error:

```
Aggregator loading search_outputs... could take some time.

 A total of 946 search_outputs and results were found.
2021-11-12 15:49:35,719 - autofit.database.aggregator.scrape - INFO - 946 searches found
2021-11-12 15:49:51,176 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo mass_total[1]_mass[total]_source 8a9db1395c049ca6e7d2ac74311e4f68
2021-11-12 15:49:51,343 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo mass_total[1]_mass[total]_source__hyper_inversion 85e2de99f7d30b1cf5e720f80722554a
2021-11-12 15:49:51,474 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[1]_mass[fixed]_source[inversion_magnification_initialization] be9400b13b1fa090c813fed798e6c914
2021-11-12 15:49:51,592 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[2]_mass[total]_source[fixed] a0d110b880895f20de3d0701fe4468d9
2021-11-12 15:49:51,685 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[3]_mass[fixed]_source[inversion_initialization] 25bea3e70de6689ed40ed9d97520f55d
2021-11-12 15:49:51,764 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[4]_mass[total]_source[fixed] 5919d92008ae473a4ab9041383b67e73
2021-11-12 15:49:51,878 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_inversion[4]_mass[total]_source[fixed]__hyper_inversion ec789a6c37cada9d663c9397bb8c0200
2021-11-12 15:49:52,112 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo source_parametric[1]_mass[total]_source[parametric] a8eea5f8d95b5b737fc6ac11b53969c8
2021-11-12 15:49:52,600 - autofit.database.aggregator.scrape - INFO - Creating fit for: no_subhalo subhalo[1]_mass[total_refine] 2aea237054b47782286f42c04f0d11ac
Traceback (most recent call last):
  File "database/build.py", line 51, in <module>
    agg.add_directory(directory=path.join("output", database_name))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 445, in add_directory
    scraper.scrape()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 58, in scrape
    for fit in self._fits():
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 103, in _fits
    identifier = _make_identifier(item)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 249, in _make_identifier
    search.unique_tag
AttributeError: 'NoneType' object has no attribute 'unique_tag'
```

Clearly the search cannot be treated as a None.
