### ISSUE TITLE
Cant pass results of phase extensions using new API

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#41]
Cant access an extended phase's results using the new API, e.g.:

`phase1.result.hyper_combined.constant.hyper_image_sky`

Gives
```

Traceback (most recent call last):
  File "/home/jammy/PycharmProjects/PyAutoLens/test/integration/tests/full_pipeline/hyper_with_lens_light_bg_new_api.py", line 287, in <module>
    runner.run(sys.modules[__name__])
  File "/home/jammy/PycharmProjects/PyAutoLens/test/integration/tests/runner.py", line 30, in run
    optimizer_class=optimizer_class,
  File "/home/jammy/PycharmProjects/PyAutoLens/test/integration/tests/full_pipeline/hyper_with_lens_light_bg_new_api.py", line 56, in make_pipeline
    hyper_galaxy=phase1.result.hyper_combined.constant.galaxies.lens.hyper_galaxy
AttributeError: 'Result' object has no attribute 'hyper_combined'
```

**Comment by rhayes777** [comment]
0.33.0 resolves this issue
