### ISSUE TITLE
update model / samples based on parameter names

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#450]
**Use case:**

There are a number of circumstances where I want to produce a set of `Samples` with a `model` that removes certain parameters. For example, below I am writing a latex string for parameter results for a paper:

```
samples_result = list(agg_result_name.values("samples"))[0]
latex = af.text.Samples.latex(samples=samples_result)
```

This string contains every parameter in the model, whereas I only want to report 3 parameters in the paper and therefore wish to remove all other parameters.

Another use case is visualization, whereby I may wish to make plots of a subset of parameters.

**Solution:**

In both the `Model` and `Samples` classes we need methods that update both, removing parameters based on their names (which comes from the model path), for example:

`model = model.keep_parameters(parameter_names=["lens_bulge_intensity", "lens_mass_centre_0"]`
`samples = samples.keep_parameters(parameter_names=["lens_bulge_intensity", "lens_mass_centre_0"]`

Here, we are left with a model that has just two parameters remaining (`lens_bulge_intensity` and `lens_mass_centre_0`).

We can also remove parameters from a model:

`model = model.remove_parameters(parameter_names=["lens_disk"]`
`samples = samples.remove_parameters(parameter_names=["lens_disk"]`

Here, all parameters which have the string `lens_disk` are removed from the model and samples.

The strings input should use `in`, such that you dont have to specify the full parameter name to remove or keep it.

When we call these methods on `Samples` it should update the `model` internal to that `Samples` object by calling the corresponding method.

**Dimension Tracking**

To use in-built visualization libraries of certain searches, we store their results in their native format. This will be tricky to maniuplate with these methods (whereas for our owb `Samples` object removing parameters is trivial).

The simplest solution to this is dimension tracking, which gives us the information we need to use the visualization libraries in a way that behaves as expected. For example, if we had a `Samples` object whose model has 10 parameters and we wanted to make a plot of the `Dynesty` results with just 3 parameters corresponding to dimensions 2, 4 6 we would call the visualization tool as follows:

```
dyplot.cornerpoints(
    results=self.samples.results,
    labels=self.model.parameter_labels_with_superscripts_latex,
    ndim=[2, 4, 6],
    **kwargs
)
```

The array `self.samples.results` is the results in the native `Dynesty` format that are difficult for us to manipulate. 

If the update / remove methods track the 1D indexes of parameters they keep (which in this case would be equal to `[2, 4, 6]` we can simply use dimension tracking to call visualization methods with the appropriate inputs to make it "appear" like the `keep` / `remove` tools are doing what a user would expect.

**Comment by Jammy2211** [comment]
If I try to filter the parameters of a specific tuple:

```
samples = samples.without_paths(
    [
        ("galaxies", "lens", "mass", "centre"),
    ]
)
```

I get the following error:

```
Traceback (most recent call last):
  File "scripts/database/tutorial_2_samples.py", line 374, in <module>
    print(samples.parameter_lists[0])
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/samples.py", line 87, in parameter_lists
    sample.parameter_lists_for_paths(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/sample.py", line 85, in parameter_lists_for_paths
    raise KeyError(
KeyError: "Could not find any of the following keys in kwargs (('galaxies', 'lens', 'mass', 'centre', 'centre_0'),)"
```

The path I specify is in the model paths though:

```
[('galaxies', 'lens', 'mass', 'centre', 'centre_0'), ('galaxies', 'lens', 'mass', 'centre', 'centre_1'), ('galaxies', 'lens', 'mass', 'elliptical_comps', 'elliptical_comps_0'), ('galaxies', 'lens', 'mass', 'elliptical_comps', 'elliptical_comps_1'), ('galaxies', 'lens', 'mass', 'einstein_radius'), ('galaxies', 'source', 'bulge', 'centre', 'centre_0'), ('galaxies', 'source', 'bulge', 'centre', 'centre_1'), ('galaxies', 'source', 'bulge', 'elliptical_comps', 'elliptical_comps_0'), ('galaxies', 'source', 'bulge', 'elliptical_comps', 'elliptical_comps_1'), ('galaxies', 'source', 'bulge', 'intensity'), ('galaxies', 'source', 'bulge', 'effective_radius'), ('galaxies', 'source', 'bulge', 'sersic_index')]
```

**Comment by Jammy2211** [comment]
It may also be good to support both of the following APIs:

`samples = samples.without_paths([("gaussian", "centre",)])`

`samples = samples.without_paths([("gaussian.centre",)])`
