### ISSUE TITLE
EP tutorial crashes after first wave of optimizers

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#459]
If I run the following tutorial:

https://github.com/Jammy2211/autofit_workspace/blob/master/scripts/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation.py

 I get the following error:

```
2022-01-14 18:14:05,045 - autofit.non_linear.initializer - INFO - Generating initial samples of model, which are subject to prior limits and other constraints.
2022-01-14 18:14:05,071 - root - INFO - No Dynesty samples found, beginning new non-linear search.
591it [00:01, 388.78it/s, +100 | bound: 18 | nc: 1 | ncall: 5104 | eff(%): 13.538 | loglstar:   -inf < 185.859 <    inf | logz: 181.790 +/-  0.242 | dlogz:  0.002 >  0.109]
2022-01-14 18:14:06,755 - root - INFO - 145000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image chi_squared_map.png
636it [00:00, 5078.57it/s, +100 | bound: 22 | nc: 1 | ncall: 5416 | eff(%): 13.589 | loglstar:   -inf < 185.859 <    inf | logz: 181.790 +/-  0.241 | dlogz:  0.001 >  0.109]
2022-01-14 18:14:07,487 - root - INFO - 150000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image chi_squared_map.png
636it [00:00, 261194.30it/s, +100 | bound: 22 | nc: 1 | ncall: 5416 | eff(%): 13.589 | loglstar:   -inf < 185.859 <    inf | logz: 181.790 +/-  0.241 | dlogz:  0.001 >  0.109]
2022-01-14 18:14:08,144 - root - INFO - 155000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image chi_squared_map.png
2022-01-14 18:14:08,614 - root - INFO - 160000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_7/optimization_0/image chi_squared_map.png
2022-01-14 18:14:11,233 - root - INFO - Removing zip file
2022-01-14 18:14:11,276 - root - INFO - Starting search
2022-01-14 18:14:11,276 - root - INFO - Saving path info
2022-01-14 18:14:11,287 - root - INFO - Not complete. Starting non-linear search.
2022-01-14 18:14:11,288 - root - INFO - number_of_cores == 1...
2022-01-14 18:14:11,289 - root - INFO - ...not using pool
2022-01-14 18:14:11,289 - autofit.non_linear.initializer - INFO - Generating initial samples of model, which are subject to prior limits and other constraints.
2022-01-14 18:14:11,316 - root - INFO - No Dynesty samples found, beginning new non-linear search.
570it [00:01, 369.37it/s, +100 | bound: 23 | nc: 1 | ncall: 5106 | eff(%): 13.122 | loglstar:   -inf < 172.681 <    inf | logz: 168.640 +/-  0.238 | dlogz:  0.002 >  0.109]
2022-01-14 18:14:12,994 - root - INFO - 165000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image chi_squared_map.png
633it [00:00, 2908.14it/s, +100 | bound: 29 | nc: 1 | ncall: 5646 | eff(%): 12.983 | loglstar:   -inf < 172.681 <    inf | logz: 168.641 +/-  0.232 | dlogz:  0.001 >  0.109]
2022-01-14 18:14:13,859 - root - INFO - 170000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image chi_squared_map.png
633it [00:00, 233467.68it/s, +100 | bound: 29 | nc: 1 | ncall: 5646 | eff(%): 12.983 | loglstar:   -inf < 172.681 <    inf | logz: 168.641 +/-  0.232 | dlogz:  0.001 >  0.109]
2022-01-14 18:14:14,529 - root - INFO - 175000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image chi_squared_map.png
2022-01-14 18:14:15,060 - root - INFO - 180000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_8/optimization_0/image chi_squared_map.png
2022-01-14 18:14:17,795 - root - INFO - Removing zip file
2022-01-14 18:14:17,839 - root - INFO - Starting search
2022-01-14 18:14:17,840 - root - INFO - Saving path info
2022-01-14 18:14:17,852 - root - INFO - Not complete. Starting non-linear search.
2022-01-14 18:14:17,853 - root - INFO - number_of_cores == 1...
2022-01-14 18:14:17,853 - root - INFO - ...not using pool
2022-01-14 18:14:17,853 - autofit.non_linear.initializer - INFO - Generating initial samples of model, which are subject to prior limits and other constraints.
2022-01-14 18:14:17,879 - root - INFO - No Dynesty samples found, beginning new non-linear search.
557it [00:01, 360.34it/s, +100 | bound: 20 | nc: 1 | ncall: 5103 | eff(%): 12.875 | loglstar:   -inf < 178.860 <    inf | logz: 173.124 +/-  0.318 | dlogz:  0.012 >  0.109]
2022-01-14 18:14:19,550 - root - INFO - 185000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image chi_squared_map.png
799it [00:00, 876.82it/s, +100 | bound: 45 | nc: 1 | ncall: 7208 | eff(%): 12.472 | loglstar:   -inf < 178.860 <    inf | logz: 173.128 +/-  0.265 | dlogz:  0.001 >  0.109]
2022-01-14 18:14:21,145 - root - INFO - 190000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image chi_squared_map.png
799it [00:00, 305994.24it/s, +100 | bound: 45 | nc: 1 | ncall: 7208 | eff(%): 12.472 | loglstar:   -inf < 178.860 <    inf | logz: 173.128 +/-  0.265 | dlogz:  0.001 >  0.109]
2022-01-14 18:14:21,930 - root - INFO - 195000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image chi_squared_map.png
2022-01-14 18:14:22,518 - root - INFO - 200000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image model_data.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image residual_map.png
output/dadacefaed2bd99700c4f7664421d5f9/dataset_9/optimization_0/image chi_squared_map.png
2022-01-14 18:14:25,255 - root - INFO - Removing zip file
2022-01-14 18:14:25,311 - PriorFactor1 - ERROR - There have been no successful optimisations for factor Factor(PriorFactor1, x=GaussianPrior, mean = 3.0, sigma = 5.0)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/expectation_propagation/history.py", line 92, in latest_successful
    return self.successes[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/expectation_propagation/optimiser.py", line 180, in _log_factor
    log_evidence = factor_history.latest_successful.log_evidence
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/expectation_propagation/history.py", line 94, in latest_successful
    raise exc.HistoryException(
autofit.exc.HistoryException: There have been no successful optimisations for factor Factor(PriorFactor1, x=GaussianPrior, mean = 3.0, sigma = 5.0)
Traceback (most recent call last):
  File "scripts/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation.py", line 179, in <module>
    collection = factor_graph.optimise(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/declarative/abstract.py", line 137, in optimise
    updated_ep_mean_field = opt.run(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/expectation_propagation/optimiser.py", line 236, in run
    model_approx, status = optimiser.optimise(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/optimise.py", line 328, in optimise
    res = opt.maximise(start, status=status, **opt_kws)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/optimise.py", line 258, in maximise
    res = self._minimise(p0, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/optimise.py", line 232, in _minimise
    return minimize(func, x0, **opt_kws)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 617, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jammy/venvs/PyAuto/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/optimise.py", line 144, in __call__
    return self.sign * np.sum(self.factor(values, axis=None))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/mean_field.py", line 384, in __call__
    fval = self.factor(values, axis=axis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/factor_graphs/factor.py", line 445, in __call__
    val = self._call_factor(**kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/graphical/factor_graphs/factor.py", line 378, in _call_factor
    return self._factor(**kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/messages/abstract.py", line 240, in factor
    self.assert_within_limits(x)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior/abstract.py", line 81, in assert_within_limits
    raise exc.PriorLimitException(
autofit.exc.PriorLimitException: The physical value -2.5931857261308178 for a prior was not within its limits 0.0, inf
```

I guess changes to prior limits have done this, albeit I'm not sure where the value of -2.5931857261308178 comes from. Does the first reoptimization  of a factor now use a Gaussian prior near an edge or something?

**Comment by rhayes777** [comment]
So this failed for me this morning but just passed twice. It might be something stochastic occaisionally causing the failure? It seems unlikely that any change made today fixed it
