### ISSUE TITLE
Project Imports taking their sweet time

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#486]
I think that AutoConf is starting to slow down in certain settings, in particular for pyautolens.

This seems to be related to config reading?

```
^CTraceback (most recent call last):
  File "preprocess/tutorial_7_los_centre.py", line 9, in <module>
    import autolens as al
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/__init__.py", line 1, in <module>
    from autoarray import preprocess
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoArray/autoarray/__init__.py", line 2, in <module>
    from . import type
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoArray/autoarray/type.py", line 7, in <module>
    from autoarray.structures.grids.two_d.grid_2d import Grid2D
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoArray/autoarray/structures/grids/two_d/grid_2d.py", line 6, in <module>
    from autoarray.structures.grids.two_d.abstract_grid_2d import AbstractGrid2D
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoArray/autoarray/structures/grids/two_d/abstract_grid_2d.py", line 4, in <module>
    from autoconf import conf
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/__init__.py", line 3, in <module>
    from .conf import Config
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/conf.py", line 260, in <module>
    default = Config(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/conf.py", line 99, in __init__
    self.configs = list(map(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/conf.py", line 171, in configs
    recurse_config(config_, self._dict)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/conf.py", line 161, in recurse_config
    recurse_config(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/conf.py", line 161, in recurse_config
    recurse_config(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/conf.py", line 161, in recurse_config
    recurse_config(
  [Previous line repeated 3 more times]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/conf.py", line 152, in recurse_config
    for key, value in config.items():
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/directory_config.py", line 19, in items
    return [(key, self[key]) for key in self.keys()]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/directory_config.py", line 102, in keys
    return [
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/directory_config.py", line 109, in <listcomp>
    os.path.isdir(
  File "/usr/lib/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
KeyboardInterrupt
```

Does every `from autoconf import conf` lead to a mass recursion?

**Comment by rhayes777** [comment]
When you import a module in python it remains cached so it's only the first import that takes any time

**Comment by Jammy2211** [comment]
Its beginning to take an extremely long time, to the point I think something may of gone wrong that has slowed it down a lot.
