### ISSUE TITLE
Parallel feature of GridSearch bugged

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#52]
Long time since we used this, and never since the promises API, so no surprise its gone buggy. in PyAutoToy using parallel=True gives this error:

```
Process 0:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/grid_search.py", line 427, in run
    self.queue.put(job.perform())
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/grid_search.py", line 387, in perform
    result = self.optimizer_instance.fit(self.analysis, self.model)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/non_linear/non_linear.py", line 293, in timed_function
    result = func(optimizer_instance, *args, **kwargs)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/non_linear/multi_nest.py", line 182, in fit
    analysis.visualize(instance=instance, during_analysis=False)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoToy/toy_gaussian/src/pipeline/phase/imaging/analysis.py", line 55, in visualize
    fit = self.masked_imaging_fit_from_instance(instance=instance)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoToy/toy_gaussian/src/pipeline/phase/imaging/analysis.py", line 44, in masked_imaging_fit_from_instance
    instance.gaussians,
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoArray/autoarray/structures/arrays.py", line 209, in in_1d_binned
    return self.mask.mapping.array_binned_from_sub_array_1d(sub_array_1d=self)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoArray/autoarray/mask/mapping.py", line 160, in array_binned_from_sub_array_1d
    self.mask.sub_fraction,
AttributeError: 'Mask' object has no attribute 'sub_fraction'
Process 1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/grid_search.py", line 427, in run
    self.queue.put(job.perform())
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/grid_search.py", line 387, in perform
    result = self.optimizer_instance.fit(self.analysis, self.model)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/non_linear/non_linear.py", line 293, in timed_function
    result = func(optimizer_instance, *args, **kwargs)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoFit/autofit/optimize/non_linear/multi_nest.py", line 182, in fit
    analysis.visualize(instance=instance, during_analysis=False)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoToy/toy_gaussian/src/pipeline/phase/imaging/analysis.py", line 55, in visualize
    fit = self.masked_imaging_fit_from_instance(instance=instance)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoToy/toy_gaussian/src/pipeline/phase/imaging/analysis.py", line 44, in masked_imaging_fit_from_instance
    instance.gaussians,
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoArray/autoarray/structures/arrays.py", line 209, in in_1d_binned
    return self.mask.mapping.array_binned_from_sub_array_1d(sub_array_1d=self)
  File "/home/jammy/PycharmProjects/PyAuto/PyAutoArray/autoarray/mask/mapping.py", line 160, in array_binned_from_sub_array_1d
    self.mask.sub_fraction,
AttributeError: 'Mask' object has no attribute 'sub_fraction'
```

Once this is running on your laptop, it would be good (if we have time) for me to test this on the Durham supercomputer.

**Comment by rhayes777** [comment]
__arrayfinalize__ was not correctly assigning this attribute in the case that a Mask was instantiated as a view for a generic ndarray
