### ISSUE TITLE
HierarchicalFactor model requires config

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#520]
The priors / messages PR has caused an issue when fitting graphical hierarchical models:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/graphical/hierarchical.py

This script gives the following error:

```
2022-05-05 09:29:08,769 - autofit.non_linear.abstract_search - INFO - Creating search
2022-05-05 09:29:08,976 - hierarchical - INFO - Starting search
Traceback (most recent call last):
  File "graphical/hierarchical.py", line 183, in <module>
    result = search.fit(model=factor_graph.global_prior_model, analysis=factor_graph)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 469, in fit
    self.paths.restore()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/abstract.py", line 310, in restore
    if path.exists(self._zip_path):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/abstract.py", line 341, in _zip_path
    return f"{self.output_path}.zip"
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/abstract.py", line 267, in output_path
    self.identifier
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/abstract.py", line 211, in identifier
    return str(self._identifier)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/abstract.py", line 201, in _identifier
    self.__identifier = Identifier(identifier_list)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 113, in __init__
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 234, in _add_value_to_hash_list
    self.add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 244, in add_value_to_hash_list
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 200, in _add_value_to_hash_list
    self.add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 244, in add_value_to_hash_list
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 209, in _add_value_to_hash_list
    self.add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 244, in add_value_to_hash_list
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 200, in _add_value_to_hash_list
    self.add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 244, in add_value_to_hash_list
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 209, in _add_value_to_hash_list
    self.add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 244, in add_value_to_hash_list
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 200, in _add_value_to_hash_list
    self.add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 244, in add_value_to_hash_list
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 209, in _add_value_to_hash_list
    self.add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 244, in add_value_to_hash_list
    self._add_value_to_hash_list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/identifier.py", line 146, in _add_value_to_hash_list
    raise value
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/prior_model.py", line 206, in make_prior
    return Prior.for_class_and_attribute_name(cls, attribute_name)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior/abstract.py", line 102, in for_class_and_attribute_name
    prior_dict = conf.instance.prior_config.for_class_and_suffix_path(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/directory_config.py", line 167, in for_class_and_suffix_path
    raise exc.ConfigException(
autoconf.exc.ConfigException: No prior config found for class:

GaussianPrior

For parameter name and path:

 lower_limit

 In any of the following directories:

/mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/config/priors /mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/config/priors

The following readthedocs page explains prior configuration files in PyAutoFit and will help you fix the error https://pyautofit.readthedocs.io/en/latest/general/adding_a_model_component.html
```

The following model component:

```
hierarchical_factor = af.HierarchicalFactor(
    af.GaussianPrior,
    mean=af.UniformPrior(lower_limit=0.0, upper_limit=100.0),
    sigma=af.UniformPrior(lower_limit=0.0, upper_limit=100.0),
)
```

Is now looking for a config, when it didn't previously (and shouldnt need it).

Adding a config file didn't seem to fix the issue.

**Comment by rhayes777** [comment]
I moved priors. You might need to update the config from

prior.prior.GaussianPrior

to
prior.gaussian.GaussianPrior

**Comment by Jammy2211** [comment]
I will try that.

Surely it should not require a prior though, because of the line:

```
hierarchical_factor = af.HierarchicalFactor(
    af.GaussianPrior,
    mean=af.UniformPrior(lower_limit=0.0, upper_limit=100.0),
    sigma=af.UniformPrior(lower_limit=0.0, upper_limit=100.0),
)
```

Which specifies the priors?

**Comment by rhayes777** [comment]
Hmm I removed some deferrence stuff because I thought it wasn't used but that could have caused it

**Comment by Jammy2211** [comment]
Ok, it turns out that in `autofit/config/priors` there is a `prior.json` file which reads:

```
{
  "GaussianPrior": {
    "lower_limit": {
      "type": "Constant",
      "value": "-inf"
    },
    "upper_limit": {
      "type": "Constant",
      "value": "inf"
    }
  }
}
```

If I rename this to `gaussian.json` as you suggested, it fixes the issue, implying the `ConfigException` behaviour was always present but this config file mitigated it.

**Comment by Jammy2211** [comment]
I now how a conflict in the `config/priors` folder between `gaussian.json` and `Gaussian.json` though haha

**Comment by rhayes777** [comment]
Erm you could probably call the directory "priors.json" and have "gaussian.GaussianPrior"

**Comment by rhayes777** [comment]
I think anyway

**Comment by Jammy2211** [comment]
Yep, just did that and it works, thanks!
