### ISSUE TITLE
Horror show of a bug

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#542]
I am running the following SLaM pipeline from autolens:

https://github.com/Jammy2211/autolens_workspace_test/blob/master/slam/no_lens_light/source_inversion/mass_total/hyper_all.py

Everything runs fine until the second search of the source inversion pipeline. Basically, the following code fails to correct pass the hyper images to the `instance` containing the galaxies:

```
    def instance_with_associated_hyper_images_from(
        self, instance: af.ModelInstance
    ) -> af.ModelInstance:
        """
        Using the model image and galaxy images that were set up as the hyper dataset, associate the galaxy images
        of that result with the galaxies in this model fit.

        Association is performed based on galaxy names, whereby if the name of a galaxy in this search matches the
        full-path name of galaxies in the hyper dataset the galaxy image is passed.

        If the galaxy collection has a different name then an association is not made.

        For example, `galaxies.lens` will match with:
            `galaxies.lens`
        but not with:
            `galaxies.source`

        Parameters
        ----------
        instance
        An instance of the model that is being fitted to the data by this analysis (whose parameters have been set
            via a non-linear search), which has 0 or more galaxies in its tree.

        Returns
        -------
        instance
           The input instance with images associated with galaxies where possible.
        """

        if self.hyper_galaxy_image_path_dict is not None:

            for galaxy_path, galaxy in instance.path_instance_tuples_for_class(Galaxy):
                if galaxy_path in self.hyper_galaxy_image_path_dict:

                    galaxy.hyper_model_image = self.hyper_model_image

                    galaxy.hyper_galaxy_image = self.hyper_galaxy_image_path_dict[
                        galaxy_path
                    ]

        return instance
```

This code works fine in previous searches and has been unchanged for a very long time.

However, If I insert the following print statements:

```

        instance = self.instance_with_associated_hyper_images_from(instance=instance)

        if self.hyper_model_image is not None:
            
            print(self.hyper_model_image)
            print(instance.galaxies.source.hyper_model_image)
```

The second print statement gives a `None` whereas the first is the correct hyper image.

The same behaviour occurs for the `hyper_galaxy_image`

```
        instance = self.instance_with_associated_hyper_images_from(instance=instance)

        if self.hyper_model_image is not None:

            print(self.hyper_galaxy_image_path_dict[("galaxies", "source")])
            print(instance.galaxies.source.hyper_galaxy_image)
```

Note that if you run the above pipeline without these source code print statements the error appears as follows (as a result of the hyper images being `None`'s:

```
Traceback (most recent call last):
  File "slam/no_lens_light/source_inversion/mass_total/hyper_all.py", line 148, in <module>
    source_inversion_results = slam.source_inversion.no_lens_light(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/source_inversion.py", line 131, in no_lens_light
    result_2 = search.fit(model=model, analysis=analysis, **settings_autofit.fit_dict)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 502, in fit
    self._fit(model=model, analysis=analysis, log_likelihood_cap=log_likelihood_cap)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/nest/dynesty/abstract.py", line 209, in _fit
    self.perform_update(model=model, analysis=analysis, during_analysis=True)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 670, in perform_update
    analysis.visualize(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/imaging/model/analysis.py", line 442, in visualize
    if fit.inversion is not None:
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/tools/decorators.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/imaging/fit_imaging.py", line 121, in inversion
    noise_map=self.noise_map,
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/imaging/fit_imaging.py", line 75, in noise_map
    return hyper_noise_map_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/imaging/fit_imaging.py", line 256, in hyper_noise_map_from
    hyper_noise_map = tracer.hyper_noise_map_from(noise_map=noise_map)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/ray_tracing.py", line 389, in hyper_noise_map_from
    return sum(self.hyper_noise_map_list_from(noise_map=noise_map))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/ray_tracing.py", line 392, in hyper_noise_map_list_from
    return [
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/ray_tracing.py", line 393, in <listcomp>
    plane.hyper_noise_map_from(noise_map=noise_map) for plane in self.planes
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoGalaxy/autogalaxy/plane/plane.py", line 275, in hyper_noise_map_from
    hyper_noise_map_list = self.hyper_noise_map_list_from(noise_map=noise_map)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoGalaxy/autogalaxy/plane/plane.py", line 294, in hyper_noise_map_list_from
    hyper_noise_map_1d = galaxy.hyper_galaxy.hyper_noise_map_via_hyper_images_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoGalaxy/autogalaxy/galaxy/galaxy.py", line 680, in hyper_noise_map_via_hyper_images_from
    contribution_map = self.contribution_map_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoGalaxy/autogalaxy/galaxy/galaxy.py", line 670, in contribution_map_from
    hyper_galaxy_image, np.add(hyper_model_image, self.contribution_factor)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

If I manually overwrite the hyper images:

```
        instance.galaxies.source.hyper_model_image = self.hyper_model_image
        instance.galaxies.source.hyper_galaxy_image = self.hyper_galaxy_image_path_dict[("galaxies", "source")]

        instance.galaxies.source.hyper_model_image = self.hyper_model_image

        if self.hyper_model_image is not None:

            print(self.hyper_model_image)
            print(instance.galaxies.source.hyper_model_image)
```

This fixes the fit, but the hyper images turn to numerical noise as if there is a memory leak in the next fit.

Worrying, making the following change to the model composition also fixes the issue:

```
            source=af.Model(
                al.Galaxy,
                redshift=result_1.instance.galaxies.source.redshift,
                pixelization=result_1.instance.galaxies.source.pixelization,
                regularization=result_1.instance.galaxies.source.regularization,
                hyper_galaxy=result_1.instance.galaxies.source.hyper_galaxy,
            ),
```

```
            source=af.Model(
                al.Galaxy,
                redshift=result_1.instance.galaxies.source.redshift,
                pixelization=result_1.model.galaxies.source.pixelization,
                regularization=result_1.instance.galaxies.source.regularization,
                hyper_galaxy=result_1.instance.galaxies.source.hyper_galaxy,
            ),
```

That is, it is specifically when these components are an `instance` this crops up...

I have dug deep on this but cannot find a root cause, and am left thinking it is to do with the way the source model is being created via prior passing that is messing with the `al.Galaxy` as a model?

**Comment by Jammy2211** [comment]
The problem is specifically because of how we are overwriting arrays in the `instance`.

The following fixes the bug (passing the hyper data throughout the source code via alternative ways):

```
    def instance_with_associated_hyper_images_from(
        self, instance: af.ModelInstance
    ) -> af.ModelInstance:
        """
        Using the model image and galaxy images that were set up as the hyper dataset, associate the galaxy images
        of that result with the galaxies in this model fit.

        Association is performed based on galaxy names, whereby if the name of a galaxy in this search matches the
        full-path name of galaxies in the hyper dataset the galaxy image is passed.

        If the galaxy collection has a different name then an association is not made.

        For example, `galaxies.lens` will match with:
            `galaxies.lens`
        but not with:
            `galaxies.source`

        Parameters
        ----------
        instance
        An instance of the model that is being fitted to the data by this analysis (whose parameters have been set
            via a non-linear search), which has 0 or more galaxies in its tree.

        Returns
        -------
        instance
           The input instance with images associated with galaxies where possible.
        """

        return instance

        if self.hyper_galaxy_image_path_dict is not None:

            for galaxy_path, galaxy in instance.path_instance_tuples_for_class(Galaxy):
                if galaxy_path in self.hyper_galaxy_image_path_dict:

                    galaxy.hyper_model_image = self.hyper_model_image

                    galaxy.hyper_galaxy_image = self.hyper_galaxy_image_path_dict[
                        galaxy_path
                    ]

        return instance
```

**Comment by Jammy2211** [comment]
The following also fixes it confirming it is how the ndarrays in `hyper_model_image` and `` pollute the model:

```
        import copy

        instance = copy.copy(instance)

        if self.hyper_galaxy_image_path_dict is not None:

            for galaxy_path, galaxy in instance.path_instance_tuples_for_class(Galaxy):
                if galaxy_path in self.hyper_galaxy_image_path_dict:
                    galaxy.hyper_model_image = self.hyper_model_image

                    galaxy.hyper_galaxy_image = self.hyper_galaxy_image_path_dict[
                        galaxy_path
                    ]

        return instance
```
