### ISSUE TITLE
Issue with result.model in multi analaysis fits

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#590]
The following test (use PYAUTOFIT_TEST_MODE=1):

https://github.com/Jammy2211/autolens_workspace/blob/release/scripts/overview/overview_7_multi_wavelength.py

Raises this exception:

```
^[[1;5DTraceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace/scripts/overview/overview_7_multi_wavelength.py", line 195, in <module>
    result_list = search.fit(model=model, analysis=analysis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/abstract_search.py", line 520, in fit
    analysis.save_results_for_aggregator(paths=self.paths, result=result)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/analysis/combined.py", line 142, in save_results_for_aggregator
    self._for_each_analysis(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/analysis/combined.py", line 118, in _for_each_analysis
    func(child_paths, analysis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/analysis/combined.py", line 137, in func
    analysis.save_results_for_aggregator(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/analysis/analysis.py", line 347, in save_results_for_aggregator
    mesh_list = ag.util.model.mesh_list_from(model=result.model)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoGalaxy/autogalaxy/analysis/model_util.py", line 63, in mesh_list_from
    for galaxy in instance.galaxies:
AttributeError: 'ModelInstance' object has no attribute 'galaxies'
```

I think thst `result.model` for multi analysis code has gone wrong.

**Comment by rhayes777** [comment]
This is because for a combined analysis (in this case a free parameter analysis) there is a different model and instance for each analysis. There is no galaxies attribute on the main model instance because there is a galaxies attribute for each model instance

**Comment by Jammy2211** [comment]
Ok, I can probably edit the source code to account for this.

I guess the wrong `instance` is being passed to `save_results_for_aggregator`, which should receive the specific `instance` for its corresponding analysis.

**Comment by rhayes777** [comment]
Good point will check if that's an easier fix

**Comment by rhayes777** [comment]
Should be fixed
