### ISSUE TITLE
Inteprolator not working for CTI use case

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#683]
The following simple 1D Gaussian example shows the interpolator working for PyAutoFit:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/interpolator/model.py

However, the example I have written for CTI does not work:

https://github.com/Jammy2211/autocti_workspace_test/blob/main/temporal/model.py

It produces the following error at the end:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/interpolator.py", line 161, in __getitem__
    return value_map[item.value]
KeyError: 1.5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autocti_workspace_test/temporal/model.py", line 222, in <module>
    instance = interpolator[interpolator.time == 1.5]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/interpolator.py", line 172, in __getitem__
    new_instance = new_instance.replacing_for_path(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/model_object.py", line 51, in replacing_for_path
    obj = getattr(new, key)
AttributeError: 'ModelInstance' object has no attribute 'parallel_trap_list'
```

**Comment by rhayes777** [comment]
Sounds like you might have changed the model since one of the included
results was generated

**Comment by Jammy2211** [comment]
Reran from scratch, but same error.

**Comment by rhayes777** [comment]
Hmm
