### ISSUE TITLE
Parameter linked floats not displaying in model.info

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#818]
In the following pipeline:

https://github.com/Jammy2211/autolens_workspace_test/blob/main/slam/integration/source_pix/mass_total/base.py

In the fit `source_pix[2]_light[fixed]_mass[fixed]_source[pix]` the parameter `pixels` is passed as follows (in the following pipeline https://github.com/Jammy2211/autolens_workspace_test/blob/main/slam/source_pix.py):

```
    if setup_adapt.mesh_pixels_fixed is not None:
        if hasattr(model_2.galaxies.source.pixelization.mesh, "pixels"):
            model_2.galaxies.source.pixelization.mesh.pixels = (
                setup_adapt.mesh_pixels_fixed
            )
```

However, the `pixels` float passed via this code does not display in `model.info`:

```
    source
        redshift                                                                1.0
        pixelization
            mesh
                weight_floor                                                    UniformPrior [149], lower_limit = 0.0, upper_limit = 1.0
                weight_power                                                    UniformPrior [150], lower_limit = 0.0, upper_limit = 20.0
            regularization
                inner_coefficient                                               LogUniformPrior [151], lower_limit = 1e-06, upper_limit = 1000000.0
                outer_coefficient                                               LogUniformPrior [152], lower_limit = 1e-06, upper_limit = 1000000.0
                signal_scale                                                    UniformPrior [153], lower_limit = 0.0, upper_limit = 1.0
```

This has caused me some confusion, and indicates that in edge cases certain parameters or fixed values are lost from `model.info` (this has also happened with tuples, which I will post a separate issue about when it crops up again and I'm reminded of it.

**Comment by rhayes777** [comment]
I actually see a multiprocessing error when I try to run slam/integration/source_pix/mass_total/base.py

```
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/autolens39/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/homebrew/anaconda3/envs/autolens39/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/other/autolens/fit/autofit/non_linear/parallel/sneaky.py", line 384, in fitness_cache
    return FunctionCache.fitness(x, *FunctionCache.fitness_args,
AttributeError: type object 'FunctionCache' has no attribute 'fitness'
```

This is Python 3.9 on a Mac. Any thoughts @jacob-hjortlund ?
