### ISSUE TITLE
Database building issue due to inheritance

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#823]
The following script fails to build a database:

https://github.com/Jammy2211/autolens_workspace_test/blob/main/database/github_issue/build.py

The issue it raises is:

```
"^[[Dremove larTraceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/database/github_issue/build.py", line 50, in <module>
    agg.add_directory(directory=path.join("output", database_name))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 419, in add_directory
    scraper.scrape()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 62, in scrape
    for fit in self._fits():
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/scrape.py", line 89, in _fits
    model = item.model
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/aggregator/search_output.py", line 161, in model
    self.__model = AbstractPriorModel.from_dict(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/model_object.py", line 243, in from_dict
    from_dict(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/dictable.py", line 156, in from_dict
    return __parsers[type_](dictionary, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/model_object.py", line 243, in from_dict
    from_dict(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/dictable.py", line 156, in from_dict
    return __parsers[type_](dictionary, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/model_object.py", line 243, in from_dict
    from_dict(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/dictable.py", line 156, in from_dict
    return __parsers[type_](dictionary, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/model_object.py", line 213, in from_dict
    return cls_(
TypeError: Isothermal.__init__() got an unexpected keyword argument 'slope'
```

This will be related to how the `slope` parameter of an `Isothermal` is not in its `__init__` constructor:

```
class Isothermal(PowerLaw):
    def __init__(
        self,
        centre: Tuple[float, float] = (0.0, 0.0),
        ell_comps: Tuple[float, float] = (0.0, 0.0),
        einstein_radius: float = 1.0,
    ):
        """
        Represents an elliptical isothermal density distribution, which is equivalent to the elliptical power-law
        density distribution for the value slope: float = 2.0

        Parameters
        ----------
        centre
            The (y,x) arc-second coordinates of the profile centre.
        ell_comps
            The first and second ellipticity components of the elliptical coordinate system.
        einstein_radius
            The arc-second Einstein radius.
        """

        super().__init__(
            centre=centre,
            ell_comps=ell_comps,
            einstein_radius=einstein_radius,
            slope=2.0,
        )
```

**Comment by rhayes777** [comment]
If I apply to_dict to an Isothermal there is no slope in the arguments. However, in the model.json file provided for this test there is a slope argument. How and when was that model.json created?

**Comment by Jammy2211** [comment]
Ok, it was made via search chaining so I guess the slope gets added due to that at some point.

Indeed, the `mass` component with the `slope` is created via this line:

`mass=source_results[0].instance.galaxies.lens.mass`

So it is when an `Isothermal` is passed using `instance`, and because the `slope` is an attribute of the model (e.g. `self.slope` is given the value 2.0 in the inheritance of the `Isothermal` class) it gets passed.

So, the problem is that when we pass things as a `instance` other attributes of the class are passed.

**Comment by rhayes777** [comment]
Still not sure I understand

**Comment by Jammy2211** [comment]
```
class Isothermal(PowerLaw):
    def __init__(
        self,
        centre: Tuple[float, float] = (0.0, 0.0),
        ell_comps: Tuple[float, float] = (0.0, 0.0),
        einstein_radius: float = 1.0,
    ):
        """
        Represents an elliptical isothermal density distribution, which is equivalent to the elliptical power-law
        density distribution for the value slope: float = 2.0

        Parameters
        ----------
        centre
            The (y,x) arc-second coordinates of the profile centre.
        ell_comps
            The first and second ellipticity components of the elliptical coordinate system.
        einstein_radius
            The arc-second Einstein radius.
        """

        self.centre = centre
        self.ell_comps = ell_comps
        self.einstein_radius = einstein_radius
        self.slope = 2.0
```

`isothermal = af.Model(Isothermal)`

The `model.json` file of this would not have a `slope` parameter.

However, if I made a new model using prior passing (e.g.)

`result = ...`

`new_isothermal = result.instance.isothermal`.

The `new_isothermal` would have a `slope` parameter equal to 2.0, because the `instance` command passes all attributes (including `self.slope`).

**Comment by rhayes777** [comment]
As far as I can tell it's not prior passing:

```python
def test_regression():
    isothermal = Isothermal(centre=(0.0, 0.0), einstein_radius=1.0)

    isothermal.slope = 3.0

    print(to_dict(isothermal))
    from_dict(to_dict(isothermal))


def test_model():
    model = Model(Isothermal)
    print(to_dict(model))
    from_dict(to_dict(model))

    instance = model.instance_from_prior_medians()
    print(to_dict(instance))
    from_dict(to_dict(instance))

**Comment by Jammy2211** [comment]
If you run this script:

https://github.com/Jammy2211/autolens_workspace_test/blob/main/slam/integration/source_lp/mass_total/base.py

The `model.info` of the `light[1]_light[lp]` search shows this:

```
        mass
            centre                                                              (-0.010113179830528594, 0.005442398116450467)
            ell_comps                                                           (-0.0005723874594002903, 0.0009181488249231434)
            einstein_radius                                                     1.5999595505559892
            slope                                                               2.0
            core_radius                                                         0.0
```

So this script can inform you where in a full autolens run these attributes are ending up in the model, which presumably is some complicated result of passing priors.

**Comment by rhayes777** [comment]
Have you rebuild the data that it's loading?

**Comment by Jammy2211** [comment]
Ok I think that was the problem... will leave open to do one final check.

**Comment by rhayes777** [comment]
Can we close this?
