### ISSUE TITLE
Add covariance.txt support to database

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#830]
An output in the `files` folder of a model-fit is the covariance matrix of the fit, as `covariance.txt`.

However, the following script: 

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/database/scrape/general.py

shows it cannot be loaded by the database:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/scripts/database/scrape/general.py", line 171, in <module>
    for covariance in agg.values("covariance"):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/aggregator/aggregator.py", line 120, in values
    value = fit[name]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/database/model/fit.py", line 310, in __getitem__
    return getattr(self, item)
AttributeError: 'Fit' object has no attribute 'covariance'
```

Can we have this as a supported quantity in the database?

I guess we need to support the plain .txt file in what a database holds, or to use a .json file so it just works.

**Comment by Jammy2211** [comment]
Its the covariance matrix, so a matrix of dimensions [total_free_parameters, total_free_parameters].

It could well be stored as a .csv or .json to reuse functionality else where.

Here is a 3x3 example:

```
1.783541160855181204e-02,-2.862926968782516460e-03,-1.337360341409695765e-03
-2.862926968782516460e-03,8.628387772503857966e-02,2.263433264011222718e-02
-1.337360341409695765e-03,2.263433264011222718e-02,1.717293641678702132e-02
```

It would also be useful to have the names of parameters aceoss the top (like for `samples.csv`):

```
           centre,       normalization,            sigma, 
1.783541160855181204e-02,-2.862926968782516460e-03,-1.337360341409695765e-03
-2.862926968782516460e-03,8.628387772503857966e-02,2.263433264011222718e-02
-1.337360341409695765e-03,2.263433264011222718e-02,1.717293641678702132e-02
```

We store covariance separate from samples (even though it can be computed from samples) because for the interpolator the covariances are used, and this will save a lot of time / storage.
