### ISSUE TITLE
Derived quantity output produces PriorLimitException

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#916]
Running many test scripts produces this error:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_pix/mass_total/base.py", line 257, in <module>
    fit()
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_pix/mass_total/base.py", line 240, in fit
    subhalo_results = slam.subhalo.detection.run(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo/detection.py", line 75, in run
    result_no_subhalo = search_no_subhalo.fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 542, in fit
    return search.fit(model=model, analysis=analysis, info=info)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 565, in fit
    result = self.start_resume_fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 687, in start_resume_fit
    samples = self.perform_update(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 925, in perform_update
    self.paths.save_derived_quantities(samples=samples)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/directory.py", line 249, in save_derived_quantities
    rows=samples.derived_quantities_list,
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/samples.py", line 116, in derived_quantities_list
    return self.derived_quantities_for_instances(self.instances)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/samples.py", line 66, in instances
    return [
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/samples.py", line 67, in <listcomp>
    self.model.instance_from_vector(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 774, in instance_from_vector
    prior.assert_within_limits(value)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior/abstract.py", line 119, in assert_within_limits
    raise exc.PriorLimitException(
autofit.exc.PriorLimitException: The physical value 3.2890903574678925 for a prior was not within its limits 1.999, 2.001
```

This is likely because whatever derived quantities its trying to output, are being giving limits via config files or something else that are invalid.

**Comment by Jammy2211** [comment]
I have fixed this by adding a `ignore_prior_limits=True` to the following property:

```
    @property
    def instances(self):
        """
        One model instance for each sample
        """
        return [
            self.model.instance_from_vector(
                sample.parameter_lists_for_paths(
                    self.paths if sample.is_path_kwargs else self.names
                ),
                ignore_prior_limits=True
            )
            for sample in self.sample_list
        ]

```

I think this makes sense, as derived quantities do not have priors and thus do not need prior limits, but you should check that this is the most sane way to fix it.

**Comment by Jammy2211** [comment]
I pushed it to a PR and merged, btw, so I can continue to test derived functionality.

**Comment by rhayes777** [comment]
That specific script fails for a different reason for me:
```python
Traceback (most recent call last):
  File "/Users/other/autolens/workspace/lens_test/slam/integration/source_pix/mass_total/base.py", line 257, in <module>
    fit()
  File "/Users/other/autolens/workspace/lens_test/slam/integration/source_pix/mass_total/base.py", line 144, in fit
    dataset=dataset, adapt_images=source_lp_results.last.adapt_images
AttributeError: 'ResultImaging' object has no attribute 'adapt_images'
```

Derived quantities don't have limits. I think the issue arose because we compute derived quantities for every sample, including those which induces a prior limit exception. In that case the fix you've added should be sufficient.
