### ISSUE TITLE
Assertions Not Working in Certain Use Case

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#941]
The following script is an autocti example script:

https://github.com/Jammy2211/autocti_workspace/blob/main/scripts/dataset_1d/modeling/start_here.py

It has the following assertion:

```
trap_0 = af.Model(ac.TrapInstantCapture)
trap_1 = af.Model(ac.TrapInstantCapture)

trap_0.add_assertion(trap_0.release_timescale < trap_1.release_timescale)

trap_list = [trap_0, trap_1]

ccd = af.Model(ac.CCDPhase)
ccd.well_notch_depth = 0.0
ccd.full_well_depth = 200000.0

model = af.Collection(cti=af.Model(ac.CTI1D, trap_list=trap_list, ccd=ccd))
```

However, the assertion is not being used, with inspection of `samples.csv` showing traps with release timescales either side of one another:

```
cti.trap_list.0.density,cti.trap_list.0.release_timescale,cti.trap_list.1.density,cti.trap_list.1.release_timescale,cti.ccd.well_fill_power,     log_likelihood,log_prior,      log_posterior,                 weight
       7.87928645193925,                30.02060575619353,       2.58545481470609,                 0.43600502569563,       0.30953621178499,             -1e+99,      0.0,             -1e+99,                    0.0
       3.84204094791698,                42.92775572503909,       8.79150801661581,                38.50302049228188,       0.73357451644737,             -1e+99,      0.0,             -1e+99,                    0.0
       1.08985009222991,                38.40474606456847,       5.15101755882098,                18.18602454636306,       0.63908143830035,             -1e+99,      0.0,             -1e+99,                    0.0
       9.50145786905749,                 0.86980230695975,       4.41701938604568,                 18.1383432802373,       0.86977740771926,-115348836.57804729,      0.0,-115348836.57804729,                    0.0
   
```

I tried the following alternative assertion API:

```
model.add_assertion(
    model.cti.trap_list[0].release_timescale < model.cti.trap_list[1].release_timescale
)
```

But again the `samples.csv` indicate the assertion is not being used.

However, I made a dediciated assertions test script in `autofit_workspace_test` and they seem to be working, so this must be specific to something about the CTI model?

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/features/assertion.py

**Comment by Jammy2211** [comment]
Ok so the alternative API at the end does produce the desired behaviour.

And the original API has worked on my super computer runs, but not on a local run, making me think this might be Python version dependent.

**Comment by rhayes777** [comment]
In the samples you do get assertion breaking results but they have very low figure of merit

**Comment by rhayes777** [comment]
What do you mean by two different APIs?

**Comment by Jammy2211** [comment]
> In the samples you do get assertion breaking results but they have very low figure of merit

yep, I forgot that is how we implemented assertions! I have taken a note to create a feature which removes these in the future.

> What do you mean by two different APIs?

The two APIs are how I setup the model in this script:

https://github.com/Jammy2211/autocti_workspace/blob/main/scripts/dataset_1d/modeling/start_here.py

```
trap_0 = af.Model(ac.TrapInstantCapture)
trap_1 = af.Model(ac.TrapInstantCapture)

# API 1:

# trap_0.add_assertion(trap_0.release_timescale < trap_1.release_timescale)

trap_list = [trap_0, trap_1]

ccd = af.Model(ac.CCDPhase)
ccd.well_notch_depth = 0.0
ccd.full_well_depth = 200000.0

model = af.Collection(cti=af.Model(ac.CTI1D, trap_list=trap_list, ccd=ccd))

# API 2:

# model.add_assertion(
#     model.cti.trap_list[0].release_timescale < model.cti.trap_list[1].release_timescale
# )
```

Having done more digging, it seems that both API's work correctly (e.g. they remove solutions where release_timescale_0 < relese_timescale_1).

The strange thing is that for API 1, the script raises the following exception at the end:

```
2024-02-19 10:33:16,713 - species[x2] - INFO - Fit Complete: Updating final results (see output folder for final visualization, samples, etc.)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autocti_workspace/scripts/dataset_1d/modeling/start_here.py", line 389, in <module>
    result_list = search.fit(model=model, analysis=analysis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 565, in fit
    result = self.start_resume_fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 700, in start_resume_fit
    analysis.save_results_combined(paths=self.paths, result=result)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/analysis/combined.py", line 199, in save_results_combined
    self.analyses[0].save_results_combined(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoCTI/autocti/model/analysis.py", line 85, in save_results_combined
    instance = sample.instance_for_model(model=result.samples.model)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/sample.py", line 194, in instance_for_model
    return model.instance_from_path_arguments(self.kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1401, in instance_from_path_arguments
    return self._instance_for_arguments(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/collection.py", line 249, in _instance_for_arguments
    value = value.instance_for_arguments(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1304, in instance_for_arguments
    instance = self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/prior_model.py", line 445, in _instance_for_arguments
    ] = prior_model.instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1304, in instance_for_arguments
    instance = self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/collection.py", line 249, in _instance_for_arguments
    value = value.instance_for_arguments(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1301, in instance_for_arguments
    self.check_assertions(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 209, in check_assertions
    raise exc.FitException(
autofit.exc.FitException: 1 assertions failed!
GreaterThanLessThanAssertion
```

Whereas for API 2 it does not.

The implication is that `check_assertions` is missing some sort of check, which depends on how the model was composed.

**Comment by rhayes777** [comment]
Just opened a PR. The ignore_assertions flag was not passed recursively so assertions attached to deeper model components would not be ignored when when constructing the invalid instances used to compute derived quantities for bad samples.

**Comment by Jammy2211** [comment]
This did appear to fix things, but the issue is cropping up again for the same test case so I guess we've lost the flag somewhere:

https://github.com/Jammy2211/autocti_workspace/blob/main/scripts/dataset_1d/modeling/start_here.py

**Comment by rhayes777** [comment]
This still seems to be working as expected, with assertions triggering and giving a likelihood of -1e+99. I can't see what this issue is?

**Comment by Jammy2211** [comment]
So when I run the above script in test mode:

`export PYAUTOFIT_TEST_MODE=1`

I get the following error (which is also crashing a number of build server tests https://github.com/Jammy2211/PyAutoBuild/actions/runs/10655105986/job/29532298267):

```
(PyAuto) jammy@DESKTOP-H143S82:/mnt/c/Users/Jammy/Code/PyAuto/autocti_workspace$ python scripts/dataset_1d/modeling/start_here.py
/home/jammy/venvs/PyAuto/lib/python3.10/site-packages/numpy/core/getlimits.py:542: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Total Free Parameters = 5

model                                                                           Collection (N=5)
    cti                                                                         CTI1D (N=5)
        trap_list                                                               Collection (N=4)
            0 - 1                                                               TrapInstantCapture (N=2)
        ccd                                                                     CCDPhase (N=1)

cti
    trap_list
        0
            density                                                             UniformPrior [0], lower_limit = 0.0, upper_limit = 10.0
            release_timescale                                                   UniformPrior [1], lower_limit = 0.0, upper_limit = 50.0
        0 - 1
            fractional_volume_none_exposed                                      0.0
            fractional_volume_full_exposed                                      0.0
        1
            density                                                             UniformPrior [2], lower_limit = 0.0, upper_limit = 10.0
            release_timescale                                                   UniformPrior [3], lower_limit = 0.0, upper_limit = 50.0
    ccd
        full_well_depth                                                         200000.0
        first_electron_fill - well_notch_depth                                  0.0
        well_fill_power                                                         UniformPrior [6], lower_limit = 0.0, upper_limit = 1.0
2024-09-06 14:36:00,066 - autofit.non_linear.search.abstract_search - WARNING - TEST MODE ON: SEARCH WILL SKIP SAMPLING


2024-09-06 14:36:00,067 - autofit.non_linear.search.abstract_search - INFO - Starting non-linear search with 1 cores.
2024-09-06 14:36:00,069 - species[x2] - INFO - The output path of this fit is /mnt/c/Users/Jammy/Code/PyAuto/autocti_workspace/output/dataset_1d/simple/species[x2]/27327e64086d6bb660ac54212bad2e97
2024-09-06 14:36:00,070 - species[x2] - INFO - Outputting pre-fit files (e.g. model.info, visualization).
2024-09-06 14:36:00,235 - species[x2] - INFO - Starting new Nautilus non-linear search (no previous samples found).
Starting the nautilus sampler...
Please report issues at github.com/johannesulf/nautilus.
Status    | Bounds | Ellipses | Networks | Calls    | f_live | N_eff | log Z
Finished  | 1      | 0        | 0        | 100      | 1.0000 | 1     | -64690.06
2024-09-06 14:36:00,566 - species[x2] - INFO - Fit Running: Updating results after 500 iterations (see output folder).
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autocti_workspace/scripts/dataset_1d/modeling/start_here.py", line 385, in <module>
    result_list = search.fit(model=model, analysis=analysis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 597, in fit
    result = self.start_resume_fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 115, in decorated
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 723, in start_resume_fit
    search_internal = self._fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/nest/nautilus/search.py", line 149, in _fit
    search_internal = self.fit_multiprocessing(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/nest/nautilus/search.py", line 265, in fit_multiprocessing
    return self.call_search(search_internal=search_internal, model=model, analysis=analysis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/nest/nautilus/search.py", line 320, in call_search
    self.perform_update(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 1007, in perform_update
    latent_samples = analysis.compute_latent_samples(samples_save)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/analysis/analysis.py", line 70, in compute_latent_samples
    sample.instance_for_model(model)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/sample.py", line 193, in instance_for_model
    return model.instance_from_path_arguments(self.kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1381, in instance_from_path_arguments
    return self._instance_for_arguments(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/collection.py", line 257, in _instance_for_arguments
    value = value.instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1286, in instance_for_arguments
    return self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/prior_model.py", line 455, in _instance_for_arguments
    ] = prior_model.instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1286, in instance_for_arguments
    return self._instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/collection.py", line 257, in _instance_for_arguments
    value = value.instance_for_arguments(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1283, in instance_for_arguments
    self.check_assertions(arguments)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 205, in check_assertions
    raise exc.FitException(
autofit.exc.FitException: 1 assertions failed!
GreaterThanLessThanAssertion
```

However, I think there is some degree of stochasticity to this, so it may depend on whether the random draws of a run are consistent with the assertion or not.

This may be a test-mode only thing, as I've yet to get the error outside of test mode, but hard to be sure.

**Comment by Jammy2211** [comment]
The fact it is happening for this line:

`analysis.compute_latent_samples(samples_save)`

Makes me think that in test mode we had it working because the initializer bypassed model mapping:

```
    def samples_from_model(
        self,
        total_points: int,
        model: AbstractPriorModel,
        fitness,
        paths: AbstractPaths,
        use_prior_medians: bool = False,
        test_mode_samples: bool = True,
        n_cores: int = 1,
    ):
        """
        Generate the initial points of the non-linear search, by randomly drawing unit values from a uniform
        distribution between the ball_lower_limit and ball_upper_limit values.

        Parameters
        ----------
        total_points
            The number of points in non-linear paramemter space which initial points are created for.
        model
            An object that represents possible instances of some model with a given dimensionality which is the number
            of free dimensions of the model.
        """

        if os.environ.get("PYAUTOFIT_TEST_MODE") == "1" and test_mode_samples:
            return self.samples_in_test_mode(total_points=total_points, model=model)
```

But since implementing latent variables we have reintroduced the use of the model in a way that assertions can be broken?

**Comment by rhayes777** [comment]
So I think the Samples generated in test mode do no adhere to the constraints leading to assertions to fail when we compute latent variables. One option would be to skip the assertions when computing latent variables?

**Comment by Jammy2211** [comment]
Sounds like a good option, there should never be a situation where you are computing latent variables from samples which break assertions, unless the code was buggy for a different reason.
